#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
    # display hours from 0 to 12
    # display minutes from 1 to 59

hours=0
minutes=1

while [[ "$hours" -lt 13 ]]; do
    echo "Hour: $hours"
    while [[ "$minutes" -lt 60 ]]; do
        echo "$minutes"
        minutes=$((minutes + 1))
    done
    minutes=1
    hours=$((hours + 1))
done